// GENERATED BY CODE! DO NOT MODIFY!
namespace Watermelon
{
	public partial class PrefsSettings
	{
		public enum Key
		{
			Vibration = 0,
			Volume = 1,
			CurrentLevelID = 2,
			ActualLevelID = 3,
			MaxLevelReached = 4,
			Coins = 5,
			RevertCount = 6,
			ShuffleCount = 7,
			TipsCount = 8,
			DailyDays = 9,
			DailyLastDay = 10,
		}
	}
}