// GENERATED BY CODE! DO NOT MODIFY!
using UnityEngine;
namespace Watermelon
{
	[System.Serializable]
	public class Sounds
	{
		public AudioClip buttonSound;
		public AudioClip winSound;
		public AudioClip itemClick;
		public AudioClip mergeSound;
	}
}